title: Aurora Bank Mobile
author: Жилюк Алина, Кравченко Елизавета, Орел Елизавета
markdown: kramdown
theme: jekyll-theme-slate
baseurl: "/tpmp-gr13a-lab9-teamprpr"
url: "https://alina-zh-123.github.io"
